#akms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-june-deployment
  namespace: june-2026-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: june-2026
  template:
      metadata:
        labels:
          batch: june-2026
      spec:
        containers:
          - name: nginx-webserver
            image: nginx
            ports:
              - containerPort: 80
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
