name: Hello World

on:
  pull_request: 
    branches:
      - main

jobs:
  hello-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Testing the hello world script
        run: echo "Welcome to the first job"
      
